create table if not exists public.kitchen_items (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null default 'other',
  location text not null default 'fridge',
  expiry_date date,
  image text,
  quantity integer,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.kitchen_items add column if not exists quantity integer;
alter table public.kitchen_items add column if not exists updated_at timestamptz not null default now();

alter table public.kitchen_items enable row level security;

drop policy if exists "Users can view their own kitchen items" on public.kitchen_items;
create policy "Users can view their own kitchen items"
  on public.kitchen_items for select
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own kitchen items" on public.kitchen_items;
create policy "Users can insert their own kitchen items"
  on public.kitchen_items for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own kitchen items" on public.kitchen_items;
create policy "Users can update their own kitchen items"
  on public.kitchen_items for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own kitchen items" on public.kitchen_items;
create policy "Users can delete their own kitchen items"
  on public.kitchen_items for delete
  using ((select auth.uid()) = user_id);

create index if not exists kitchen_items_user_id_idx
  on public.kitchen_items(user_id);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null,
  platform text not null default 'web',
  user_agent text,
  updated_at timestamptz not null default now(),
  unique (user_id, token)
);

alter table public.push_subscriptions add column if not exists user_agent text;

alter table public.push_subscriptions enable row level security;

drop policy if exists "Users can manage their own push subscriptions" on public.push_subscriptions;
create policy "Users can manage their own push subscriptions"
  on public.push_subscriptions for all
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create index if not exists push_subscriptions_user_id_idx
  on public.push_subscriptions(user_id);

create table if not exists public.push_notification_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kitchen_item_id uuid not null references public.kitchen_items(id) on delete cascade,
  reminder_date date not null,
  created_at timestamptz not null default now(),
  unique (user_id, kitchen_item_id, reminder_date)
);

alter table public.push_notification_log enable row level security;

drop policy if exists "Users can view their own push notification log" on public.push_notification_log;
create policy "Users can view their own push notification log"
  on public.push_notification_log for select
  using ((select auth.uid()) = user_id);

create index if not exists push_notification_log_reminder_idx
  on public.push_notification_log(reminder_date);

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_preferences enable row level security;

drop policy if exists "Users can manage their own preferences" on public.user_preferences;
create policy "Users can manage their own preferences"
  on public.user_preferences for all
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  email text,
  avatar_url text,
  updated_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.user_profiles;
create policy "Users can view their own profile"
  on public.user_profiles for select
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can manage their own profile" on public.user_profiles;
create policy "Users can manage their own profile"
  on public.user_profiles for all
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
