import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    storage: 'Storage',
    add: 'Add',
    recipes: 'Recipes',
    profile: 'Profile',
    kitchenManager: 'Kitchen Manager',
    settings: 'Settings',
    manageAccount: 'Manage your account and preferences',
    account: 'Account',
    guestMode: 'Guest mode',
    notifications: 'Notifications',
    masterNotifications: 'Master Notifications',
    expiringReminders: 'Expiring Food Reminders',
    inventory: 'Inventory',
    appearance: 'Appearance',
    language: 'Language',
    appLanguage: 'App language preference',
    about: 'About the App',
    help: 'Help & Feedback',
    terms: 'Terms & Privacy',
    logOut: 'Log Out',
    addToKitchen: 'Add to Kitchen',
    photoOrGallery: 'Take a photo or pick from gallery',
    openCamera: 'Open Camera',
    skip: 'Skip',
    whatAdding: 'What are you adding?',
    searchIngredient: 'Search for an ingredient...',
    allCategories: 'All categories',
    custom: 'Custom',
    noResults: 'No results found',
    addCustom: 'Add',
    browseCategories: 'Browse Categories',
    recentlyAdded: 'Recently added',
    cancel: 'Cancel',
    confirm: 'Confirm',
    keepIt: 'Where will you keep it?',
    fridge: 'Fridge',
    freezer: 'Freezer',
    cabinet: 'Cabinet',
    pantry: 'Pantry',
    everydayStorage: 'Everyday storage',
    longTermStorage: 'Long-term storage',
    dryGoods: 'Dry goods',
    roomTemperature: 'Room temperature',
    back: 'Back',
    noExpiry: 'No expiry needed!',
    longLasting: 'can last a long time',
    checkPackage: 'Check the package',
    enterExpiryLabel: 'Enter the expiry date from the label',
    expiryDate: 'Expiry Date',
    selected: 'Selected',
    addItem: 'Add Item',
    selectDate: 'Select a date',
    whenExpire: 'When does it expire?',
    notRecommended: 'Not recommended to store in',
    exactDate: 'Choose exact date',
    noExpiryShort: 'No expiry',
    enterExpiry: 'Enter Expiry Date',
    checkLabel: 'Check the label on your',
    pickDate: 'Pick a date',
    backToOptions: 'Back to options',
    category_vegetable: 'Vegetables',
    category_fruit: 'Fruits',
    category_meat: 'Meat & Fish',
    category_dairy: 'Dairy & Eggs',
    category_bread: 'Bakery',
    category_packaged: 'Packaged',
    totalItems: 'Total Items', expiring: 'Expiring', expired: 'Expired', freshItems: 'Fresh Items',
    aiRecipeIdeas: 'AI Recipe Ideas', aiThinking: 'AI is thinking of recipes for you...',
    freshHealthy: 'Fresh & Healthy', kitchenEmpty: 'Your kitchen is empty', startAdding: 'Start adding items to get recipe suggestions!', emptyRecipeTitle: 'Add items to your kitchen first!', emptyRecipeSubtitle: 'Tap + and add ingredients to get AI recipes',
    location: 'Location', category: 'Category', sortBy: 'Sort by', estimatedExpiry: 'Estimated Expiry',
    foodCheck: 'Food Check', stillGood: 'Is it still good?', deleteItem: 'Delete Item?',
    familyPantry: 'Family Pantry', data: 'Data', exportInventory: 'Export Inventory', importInventory: 'Import Inventory',
    clearLocalData: 'Clear Local Data', resetPreferences: 'Reset Preferences', appVersion: 'App Version',
    currentVersion: 'Current version', theme: 'Theme', system: 'System', light: 'Light', dark: 'Dark',
    english: 'English', burmese: 'Burmese', logoutConfirm: 'Are you sure you want to log out?',
    viewAll: 'View all', searchYourItems: 'Search your items...', searchItems: 'Search items...',
    items: 'items', item: 'item', days: 'days', day: 'day', clearResults: 'Clear results',
    noItemsFound: 'No items found', fresh: 'Fresh', checkMe: 'Check me',
    inviteCode: 'Invite code', viewMembers: 'View members', inviteMembers: 'Invite members', leaveFamily: 'Leave family',
    deleteFamily: 'Delete family', newCode: 'New code', createPantry: 'Create pantry', joinPantry: 'Join pantry',
    familyMember: 'Family member', host: 'Host', member: 'Member', done: 'Done', close: 'Close',
    refresh: 'Refresh', findMyDish: 'Find My Dish', save: 'Save', saved: 'Saved', saving: 'Saving...',
    missing: 'Missing', partial: 'Partial', ready: 'Ready', ingredients: 'ingredients', noRecipes: 'recipes',
    allIngredientsReady: 'All ingredients ready!', ingredientsAvailable: 'ingredients available', step: 'Step',
    cookingSteps: 'Cooking Steps', letsCook: "Let's Cook", nextStep: 'Next step', back: 'Back', doneCooking: 'Done cooking',
    inventoryUpdated: 'Inventory updated', selectedIngredientsRemoved: 'The ingredients you selected were removed from your inventory.',
    whichIngredientsUsed: 'Which ingredients did you use?', onlyCheckedRemoved: 'Only checked items below will be removed. Pantry staples such as salt and oil are not included.',
    noMatchingItems: 'No matching inventory items to remove.', removeSelected: 'Remove selected items', keepInventory: 'Keep inventory', cookingHelper: 'Cooking helper',
    missingIngredientAsk: 'Missing an ingredient? Ask...', ask: 'Ask', ingredientsTitle: 'Ingredients', missingIngredients: 'Missing Ingredients',
    sharedPantryDescription: 'Share this code or link with family. Changes to this pantry appear for everyone.',
    expiryReminderDescription: 'Get notified before items expire', dayBefore: 'day before', daysBefore: 'days before',
    autoDeleteDescription: 'Remove expired food after a chosen delay', deleteAfter: 'Delete after', deleteAfterDescription: 'Choose when expired items get removed',
    systemPreference: 'Follow system preference', darkMode: 'Dark mode', lightMode: 'Light mode',
    exportDescription: 'Export your inventory as CSV', importDescription: 'Import inventory from a CSV file',
    clearDataDescription: 'Remove all cached data', resetDescription: 'Restore all settings to defaults',
    currentVersionDescription: 'Current version', aboutDescription: 'Learn more about us', feedbackDescription: 'Report a problem or suggest a feature', termsDescription: 'Privacy policy, terms of use',
    expiryReminderLabel: 'Expiry Reminder', autoDeleteExpiredItems: 'Auto-delete Expired Items',
    expiredRemovalWarning: 'Expired items will be permanently removed after expiry.',
    profileInfo: 'Profile Info', username: 'Username', email: 'Email', emailCannotChange: 'This is the email used for your account and cannot be changed here.', saveProfile: 'Save Profile', savingProfile: 'Saving...', updateProfile: 'Update your profile details',
    helpFeedback: 'Help & Feedback', feedbackType: 'Feedback type', problem: 'Problem', suggestion: 'Suggestion', categoryLabel: 'Category', message: 'Message', feedbackPlaceholder: 'Tell us what happened or what you would like improved.', sendFeedback: 'Send Feedback', sending: 'Sending...',
    welcomeBack: 'Welcome back', createAccount: 'Create your account', loginSubtitle: 'Sign in with your username, email, or Google.', signupSubtitle: 'Choose a username and create your kitchen account.', usernameOrEmail: 'Username or email', password: 'Password', continueEmail: 'Continue with email', createAccountButton: 'Create account', or: 'or', continueGoogle: 'Continue with Google', connecting: 'Connecting...', goBack: 'Back',
    itemDetails: 'Item Details', added: 'Added', estimatedExpiry: 'Estimated Expiry', noExpiryDate: 'No expiry date set', edit: 'Edit', delete: 'Delete',
    foodCheckTitle: 'Food Check', estimatedExpiryShort: 'Estimated expiry', noLongerGood: 'No longer good', stillGoodTitle: 'Still good!', extendExpiryQuestion: 'How many more days should we add?',
    current: 'Current', saveDate: 'Save Date', notRecommendedShort: 'Not recommended', noItemsMatching: 'No items matching', tryDifferentSearch: 'Try a different search term', storageEmpty: 'Your storage is empty', startAddingItems: 'Start adding items to your kitchen!',
    deleteConfirm: 'Are you sure you want to delete', cannotUndo: 'This action cannot be undone.', globalNotificationToggle: 'Global notification toggle', recipeRecommendations: 'Recipe Recommendations', personalizedRecipeSuggestions: 'Personalized recipe suggestions',
    freshKitchenMessage: 'Fresh ingredients make the best meals!', kitchenFreshPercent: 'of your kitchen is fresh', readyToUse: 'ready to use!', chooseCategory: 'Choose category',
  },
  mm: {
    home: 'ပင်မ',
    storage: 'သိုလှောင်ခန်း',
    add: 'ထည့်ရန်',
    recipes: 'ချက်ပြုတ်နည်းများ',
    profile: 'ကိုယ်ရေးအချက်အလက်',
    kitchenManager: 'မီးဖိုချောင် စီမံခန့်ခွဲမှု',
    settings: 'ဆက်တင်များ',
    manageAccount: 'အကောင့်နှင့် စိတ်ကြိုက်ရွေးချယ်မှုများကို စီမံပါ',
    account: 'အကောင့်',
    guestMode: 'ဧည့်သည်မုဒ်',
    notifications: 'အသိပေးချက်များ',
    masterNotifications: 'အသိပေးချက် အားလုံး',
    expiringReminders: 'သက်တမ်းကုန်ဆုံးမည့် အစားအစာ သတိပေးချက်',
    inventory: 'ပစ္စည်းစာရင်း',
    appearance: 'အသွင်အပြင်',
    language: 'ဘာသာစကား',
    appLanguage: 'အက်ပ် ဘာသာစကား ရွေးချယ်မှု',
    about: 'အက်ပ်အကြောင်း',
    help: 'အကူအညီနှင့် အကြံပြုချက်',
    terms: 'စည်းမျဉ်းနှင့် ကိုယ်ရေးလုံခြုံမှု',
    logOut: 'ထွက်ရန်',
    addToKitchen: 'မီးဖိုချောင်ထဲ ထည့်ရန်',
    photoOrGallery: 'ဓာတ်ပုံရိုက်ပါ သို့မဟုတ် ပြခန်းမှ ရွေးပါ',
    openCamera: 'ကင်မရာဖွင့်ရန်',
    skip: 'ကျော်ရန်',
    whatAdding: 'ဘာကို ထည့်မလဲ?',
    searchIngredient: 'ပါဝင်ပစ္စည်း ရှာရန်...',
    allCategories: 'အမျိုးအစားအားလုံး',
    custom: 'စိတ်ကြိုက်',
    noResults: 'ရလဒ် မတွေ့ပါ',
    addCustom: 'ထည့်ရန်',
    browseCategories: 'အမျိုးအစားများ ကြည့်ရန်',
    recentlyAdded: 'မကြာသေးမီက ထည့်ထားသည်',
    cancel: 'ပယ်ဖျက်ရန်',
    confirm: 'အတည်ပြုရန်',
    keepIt: 'ဘယ်နေရာမှာ သိမ်းမလဲ?',
    fridge: 'ရေခဲသေတ္တာ',
    freezer: 'အေးခဲသေတ္တာ',
    cabinet: 'ဗီရို',
    pantry: 'စားစရာခန်း',
    everydayStorage: 'နေ့စဉ်သိမ်းဆည်းရန်',
    longTermStorage: 'ရေရှည်သိမ်းဆည်းရန်',
    dryGoods: 'ခြောက်သွေ့ပစ္စည်းများ',
    roomTemperature: 'အခန်းအပူချိန်',
    back: 'နောက်သို့',
    noExpiry: 'သက်တမ်းကုန်ရက် မလိုပါ!',
    longLasting: 'ကြာရှည်ခံနိုင်သည်',
    checkPackage: 'ထုပ်ပိုးမှုကို စစ်ဆေးပါ',
    enterExpiryLabel: 'တံဆိပ်ပေါ်မှ သက်တမ်းကုန်ရက် ထည့်ပါ',
    expiryDate: 'သက်တမ်းကုန်ရက်',
    selected: 'ရွေးထားသည်',
    addItem: 'ပစ္စည်း ထည့်ရန်',
    selectDate: 'ရက်စွဲ ရွေးရန်',
    whenExpire: 'ဘယ်အချိန် သက်တမ်းကုန်မလဲ?',
    notRecommended: 'ဤနေရာတွင် သိမ်းရန် မသင့်တော်ပါ',
    exactDate: 'ရက်အတိအကျ ရွေးရန်',
    noExpiryShort: 'သက်တမ်းမရှိ',
    enterExpiry: 'သက်တမ်းကုန်ရက် ထည့်ရန်',
    checkLabel: 'သင့်',
    pickDate: 'ရက်စွဲ ရွေးရန်',
    backToOptions: 'ရွေးချယ်စရာများသို့ ပြန်ရန်',
    category_vegetable: 'ဟင်းသီးဟင်းရွက်',
    category_fruit: 'သစ်သီး',
    category_meat: 'အသားနှင့် ငါး',
    category_dairy: 'နို့ထွက်နှင့် ဥ',
    category_bread: 'မုန့်',
    category_packaged: 'ထုပ်ပိုးထားသော',
    totalItems: 'ပစ္စည်းစုစုပေါင်း', expiring: 'သက်တမ်းကုန်ရန်နီးသော', expired: 'သက်တမ်းကုန်ပြီး', freshItems: 'လတ်ဆတ်သောပစ္စည်းများ',
    aiRecipeIdeas: 'AI ချက်ပြုတ်နည်း အကြံပြုချက်များ', aiThinking: 'သင့်အတွက် ချက်ပြုတ်နည်းများ စဉ်းစားနေသည်...',
    freshHealthy: 'လတ်ဆတ်ပြီး ကျန်းမာရေးနှင့်ညီညွတ်သော', kitchenEmpty: 'မီးဖိုချောင်တွင် ပစ္စည်းမရှိသေးပါ', startAdding: 'ချက်ပြုတ်နည်း အကြံပြုချက်များရရန် ပစ္စည်းများ စတင်ထည့်ပါ။', emptyRecipeTitle: 'ပထမဆုံး မီးဖိုချောင်ထဲ ပစ္စည်းထည့်ပါ', emptyRecipeSubtitle: 'AI ချက်ပြုတ်နည်းများရရန် + ကိုနှိပ်ပြီး ပါဝင်ပစ္စည်းများ ထည့်ပါ',
    location: 'သိမ်းဆည်းရာနေရာ', category: 'အမျိုးအစား', sortBy: 'စီစဉ်ရန်', estimatedExpiry: 'ခန့်မှန်းသက်တမ်းကုန်ရက်',
    foodCheck: 'အစားအစာ စစ်ဆေးခြင်း', stillGood: 'စားသုံးရန်ကောင်းသေးပါသလား?', deleteItem: 'ပစ္စည်းကို ဖျက်မလား?',
    familyPantry: 'မိသားစု စားစရာခန်း', data: 'ဒေတာ', exportInventory: 'ပစ္စည်းစာရင်း ထုတ်ယူရန်', importInventory: 'ပစ္စည်းစာရင်း ထည့်သွင်းရန်',
    clearLocalData: 'စက်တွင်းဒေတာ ရှင်းရန်', resetPreferences: 'ရွေးချယ်မှုများ ပြန်သတ်မှတ်ရန်', appVersion: 'အက်ပ်ဗားရှင်း',
    currentVersion: 'လက်ရှိဗားရှင်း', theme: 'အပြင်အဆင်', system: 'စနစ်အတိုင်း', light: 'အလင်း', dark: 'အမှောင်',
    english: 'အင်္ဂလိပ်', burmese: 'မြန်မာ', logoutConfirm: 'အကောင့်မှ ထွက်ရန် သေချာပါသလား?',
    viewAll: 'အားလုံးကြည့်ရန်', searchYourItems: 'သင့်ပစ္စည်းများကို ရှာရန်...', searchItems: 'ပစ္စည်းများ ရှာရန်...',
    items: 'ပစ္စည်း', item: 'ပစ္စည်း', days: 'ရက်', day: 'ရက်', clearResults: 'ရလဒ်များ ရှင်းရန်',
    noItemsFound: 'ပစ္စည်း မတွေ့ပါ', fresh: 'လတ်ဆတ်', checkMe: 'စစ်ဆေးပါ',
    inviteCode: 'ဖိတ်ခေါ်ကုဒ်', viewMembers: 'အဖွဲ့ဝင်များ ကြည့်ရန်', inviteMembers: 'အဖွဲ့ဝင်များ ဖိတ်ရန်', leaveFamily: 'မိသားစုမှ ထွက်ရန်',
    deleteFamily: 'မိသားစု ဖျက်ရန်', newCode: 'ကုဒ်အသစ်', createPantry: 'စားစရာခန်း ဖန်တီးရန်', joinPantry: 'စားစရာခန်း ဝင်ရန်',
    familyMember: 'မိသားစုအဖွဲ့ဝင်', host: 'ပိုင်ရှင်', member: 'အဖွဲ့ဝင်', done: 'ပြီးပါပြီ', close: 'ပိတ်ရန်',
    refresh: 'ပြန်လည်ပြင်ဆင်ရန်', findMyDish: 'ကျွန်ုပ်အတွက် ဟင်းလျာရှာရန်', save: 'သိမ်းရန်', saved: 'သိမ်းထားသည်', saving: 'သိမ်းနေသည်...',
    missing: 'မရှိပါ', partial: 'တစ်စိတ်တစ်ပိုင်း', ready: 'အဆင်သင့်', ingredients: 'ပါဝင်ပစ္စည်းများ', noRecipes: 'ချက်ပြုတ်နည်းများ',
    allIngredientsReady: 'ပါဝင်ပစ္စည်းအားလုံး အဆင်သင့်!', ingredientsAvailable: 'ပါဝင်ပစ္စည်း ရှိသည်', step: 'အဆင့်',
    cookingSteps: 'ချက်ပြုတ်ရန် အဆင့်များ', letsCook: 'ချက်ပြုတ်ကြမယ်', nextStep: 'နောက်အဆင့်', back: 'နောက်သို့', doneCooking: 'ချက်ပြုတ်ပြီးပါပြီ',
    inventoryUpdated: 'ပစ္စည်းစာရင်း ပြင်ဆင်ပြီးပါပြီ', selectedIngredientsRemoved: 'သင်ရွေးထားသော ပါဝင်ပစ္စည်းများကို ပစ္စည်းစာရင်းမှ ဖယ်ရှားပြီးပါပြီ။',
    whichIngredientsUsed: 'ဘယ်ပါဝင်ပစ္စည်းတွေကို သုံးခဲ့ပါသလဲ?', onlyCheckedRemoved: 'အောက်တွင် အမှန်ခြစ်ထားသော ပစ္စည်းများကိုသာ ဖယ်ရှားပါမည်။ ဆားနှင့် ဆီကဲ့သို့ အခြေခံပစ္စည်းများ မပါဝင်ပါ။',
    noMatchingItems: 'ဖယ်ရှားရန် ကိုက်ညီသော ပစ္စည်းမရှိပါ။', removeSelected: 'ရွေးထားသော ပစ္စည်းများ ဖယ်ရှားရန်', keepInventory: 'ပစ္စည်းစာရင်းတွင် ထားရန်', cookingHelper: 'ချက်ပြုတ်ရေး အကူ',
    missingIngredientAsk: 'ပါဝင်ပစ္စည်း မရှိပါသလား? မေးမြန်းပါ...', ask: 'မေးရန်', ingredientsTitle: 'ပါဝင်ပစ္စည်းများ', missingIngredients: 'မရှိသော ပါဝင်ပစ္စည်းများ',
    sharedPantryDescription: 'ဤကုဒ် သို့မဟုတ် လင့်ခ်ကို မိသားစုနှင့် မျှဝေပါ။ စားစရာခန်းပြောင်းလဲမှုများကို အားလုံးမြင်ရပါမည်။',
    expiryReminderDescription: 'ပစ္စည်းသက်တမ်းမကုန်မီ အသိပေးရန်', dayBefore: 'ရက် ကြိုတင်', daysBefore: 'ရက် ကြိုတင်',
    autoDeleteDescription: 'သတ်မှတ်ထားသောအချိန်အတိုင်း သက်တမ်းကုန်ပစ္စည်းများကို ဖယ်ရှားရန်', deleteAfter: 'ဖျက်ရန် ကြာချိန်', deleteAfterDescription: 'သက်တမ်းကုန်ပစ္စည်းများကို ဘယ်အချိန်ဖယ်ရှားမလဲ ရွေးပါ',
    systemPreference: 'စနစ်အတိုင်း လိုက်နာရန်', darkMode: 'အမှောင်မုဒ်', lightMode: 'အလင်းမုဒ်',
    exportDescription: 'သင့်ပစ္စည်းစာရင်းကို CSV အဖြစ် ထုတ်ယူရန်', importDescription: 'CSV မှ ပစ္စည်းစာရင်း ထည့်သွင်းရန်',
    clearDataDescription: 'သိမ်းထားသော ဒေတာအားလုံးကို ဖယ်ရှားရန်', resetDescription: 'ဆက်တင်များအားလုံးကို မူလအတိုင်း ပြန်ထားရန်',
    currentVersionDescription: 'လက်ရှိဗားရှင်း', aboutDescription: 'ကျွန်ုပ်တို့အကြောင်း လေ့လာရန်', feedbackDescription: 'ပြဿနာတင်ပြရန် သို့မဟုတ် အကြံပြုချက်ပေးရန်', termsDescription: 'ကိုယ်ရေးလုံခြုံမှု မူဝါဒနှင့် အသုံးပြုမှုစည်းမျဉ်းများ',
    expiryReminderLabel: 'သက်တမ်းကုန်ရက် သတိပေးချက်', autoDeleteExpiredItems: 'သက်တမ်းကုန်ပစ္စည်းများ အလိုအလျောက်ဖျက်ရန်',
    expiredRemovalWarning: 'သက်တမ်းကုန်ပစ္စည်းများကို သက်တမ်းကုန်ပြီးနောက် အပြီးဖယ်ရှားပါမည်။',
    profileInfo: 'ကိုယ်ရေးအချက်အလက်', username: 'အသုံးပြုသူအမည်', email: 'အီးမေးလ်', emailCannotChange: 'ဤအီးမေးလ်သည် သင့်အကောင့်အတွက်ဖြစ်ပြီး ဤနေရာတွင် ပြောင်းလဲ၍မရပါ။', saveProfile: 'ပရိုဖိုင် သိမ်းရန်', savingProfile: 'သိမ်းနေသည်...', updateProfile: 'သင့်ပရိုဖိုင်အချက်အလက်ကို ပြင်ဆင်ရန်',
    helpFeedback: 'အကူအညီနှင့် အကြံပြုချက်', feedbackType: 'အကြံပြုချက် အမျိုးအစား', problem: 'ပြဿနာ', suggestion: 'အကြံပြုချက်', categoryLabel: 'အမျိုးအစား', message: 'စာ', feedbackPlaceholder: 'ဖြစ်ပျက်ခဲ့သည်များ သို့မဟုတ် ပြင်ဆင်လိုသည်များကို ရေးပါ။', sendFeedback: 'အကြံပြုချက် ပေးပို့ရန်', sending: 'ပေးပို့နေသည်...',
    welcomeBack: 'ပြန်လည်ကြိုဆိုပါသည်', createAccount: 'သင့်အကောင့် ဖန်တီးရန်', loginSubtitle: 'သင့်အသုံးပြုသူအမည်၊ အီးမေးလ် သို့မဟုတ် Google ဖြင့် ဝင်ရောက်ပါ။', signupSubtitle: 'အသုံးပြုသူအမည်ရွေးပြီး မီးဖိုချောင်အကောင့် ဖန်တီးပါ။', usernameOrEmail: 'အသုံးပြုသူအမည် သို့မဟုတ် အီးမေးလ်', password: 'စကားဝှက်', continueEmail: 'အီးမေးလ်ဖြင့် ဆက်လုပ်ရန်', createAccountButton: 'အကောင့်ဖန်တီးရန်', or: 'သို့မဟုတ်', continueGoogle: 'Google ဖြင့် ဆက်လုပ်ရန်', connecting: 'ချိတ်ဆက်နေသည်...', goBack: 'နောက်သို့',
    itemDetails: 'ပစ္စည်းအသေးစိတ်', added: 'ထည့်သွင်းသည့်ရက်', estimatedExpiry: 'ခန့်မှန်းသက်တမ်းကုန်ရက်', noExpiryDate: 'သက်တမ်းကုန်ရက် မသတ်မှတ်ထားပါ', edit: 'ပြင်ရန်', delete: 'ဖျက်ရန်',
    foodCheckTitle: 'အစားအစာ စစ်ဆေးခြင်း', estimatedExpiryShort: 'ခန့်မှန်းသက်တမ်းကုန်ရက်', noLongerGood: 'စားသုံးရန် မကောင်းတော့ပါ', stillGoodTitle: 'ကောင်းသေးသည်!', extendExpiryQuestion: 'ရက်ဘယ်နှရက် ထပ်တိုးမလဲ?',
    current: 'လက်ရှိ', saveDate: 'ရက်စွဲ သိမ်းရန်', notRecommendedShort: 'မသင့်တော်ပါ', noItemsMatching: 'ကိုက်ညီသော ပစ္စည်းမရှိပါ', tryDifferentSearch: 'အခြားရှာဖွေစကားလုံးဖြင့် စမ်းပါ', storageEmpty: 'သိုလှောင်ခန်း ဗလာဖြစ်နေပါသည်', startAddingItems: 'မီးဖိုချောင်ထဲ ပစ္စည်းများ စတင်ထည့်ပါ!', deleteConfirm: 'ဖျက်ရန် သေချာပါသလား', cannotUndo: 'ဤလုပ်ဆောင်ချက်ကို ပြန်ပြင်၍မရပါ။', globalNotificationToggle: 'အသိပေးချက်အားလုံးကို ထိန်းချုပ်ရန်', recipeRecommendations: 'ချက်ပြုတ်နည်း အကြံပြုချက်များ', personalizedRecipeSuggestions: 'သင့်အတွက် ကိုယ်ပိုင်အကြံပြုချက်များ',
    freshKitchenMessage: 'လတ်ဆတ်သော ပါဝင်ပစ္စည်းများဖြင့် အကောင်းဆုံးဟင်းလျာများ ချက်ပြုတ်နိုင်ပါသည်!', kitchenFreshPercent: 'မီးဖိုချောင်၏ လတ်ဆတ်မှု', readyToUse: 'အသုံးပြုရန် အဆင်သင့်!', chooseCategory: 'အမျိုးအစား ရွေးရန်',
  },
};

const LanguageContext = createContext(null);
const fallbackLanguage = {
  language: 'en',
  setLanguage: () => {},
  t: (key) => translations.en[key] || key,
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('appLanguage') || 'en');

  const setLanguage = (nextLanguage) => {
    const value = nextLanguage === 'mm' ? 'mm' : 'en';
    localStorage.setItem('appLanguage', value);
    setLanguageState(value);
  };

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.en[key] || key,
  }), [language]);

  useEffect(() => {
    document.documentElement.lang = language === 'mm' ? 'my' : 'en';
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  return context || fallbackLanguage;
}